### ISSUE TITLE
OFSET LIMIT Optimisation

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#108]
It takes time to read record from last page. 

https://stackoverflow.com/questions/14468586/efficient-paging-in-sqlite-with-millions-of-records/14468878#14468878

**Comment by ysard** [comment]
Is it possible to have again the small button allowing to see the SQL query executed in a messageBox (like on master)?

**Comment by dridk** [comment]
Yes, you can add it . 
If you try to optimize it, test with an exome file .

**Comment by ysard** [comment]
In fact I'm asking how to add it or if you could add this button. This part of code was refactored since 1 year and i don't know where to look at...

Yes exome 1.7GB

**Comment by dridk** [comment]
okay, just asign to myself !

**Comment by ysard** [comment]
Well this issue is definitely an interesting question...

We have to be smart here. I know how to provide optimizations for contiguous pagination (page 1 to 2, 2 to 3, and 3 to 2, 2 to 1, etc.).
I will need to make not insignificant changes to the way pagination is currently managed.

For random jump it is another challenge.
The easiest way is to do like SQLiteBrowser does: query and put in cache thousands of pages at a time (50000 rows in this case).
We could easily retrieve 10 000 results: 200 pages.
So when next/previous random jump is made we are in fact querying the model and not the DB.

Using these 2 methods we could have a very responsive UI.

@dridk Can you implement: such over retrieving in the model ? Or put here a draft for the update procedure.

**Comment by dridk** [comment]
we may use QContiguousCache
https://doc.qt.io/qt-5/qcontiguouscache.html

or just a simple QCache . 

by the way, since ThreadSql, this optimization does not urge
