### ISSUE TITLE
Remove automatically all fields with no information

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#114]
Some fields can be None for all variants... remove them !

**Comment by dridk** [comment]
@klva @ysard  Question : 

Do we have to check empty columns first from the VCF file before importing into sqlite ? That's mean, read the entire file. 
OR 
Import everything and remove column after

**Comment by ysard** [comment]
Good question... don't know for now

**Comment by ysard** [comment]
Validation of data is mandatory before database insertion.
But:
- We can't read 2 times the given file
- We will not modify the standard DB structure because of some empty fields
- Reconstruct DB file after the creation is time consuming
- Deletion of 1 empty field in DB is quite useless (probably no gain of space, and no gain of performance)

Maybe we could launch, after project creation, some routines to detect these fields and add them to the `State()` object in a variable `masked` fields or something like this.
Hide them only in GUI should be OK.
