### ISSUE TITLE
[ importWizard] progress bar is still wrong



### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#157]
When importing a huge vcf, progress bar is wrong. Importing continue after 100%.   You can test it with a full genome

ftp:/­/­ftp.­1000genomes.­ebi.­ac.­uk/­vol1/­ftp/­data_collections/­1000_genomes_project/­release/­20190312_biallelic_SNV_and_INDEL/­ALL.­chr17.­shapeit2_integrated_snvindels_v2a_27022019.­GRCh38.­phased.­vcf.­gz

VCFReader must return a good estimation of the total variant. 

It may useful to read the vcf in 2 pass.. It will takes double time, but we can then check for variant count and non empty field to import .

**Comment by ysard** [comment]
Evaluation of the number of variants is now quite accurate.
There is an average of 5 seconds delay, needed to evaluate the number of variants in a 1.8GB VCF file with 3.8 million of variants, after about 20 minutes of insertion in database.

For much smaller files the delay is negligible.

Thus now we open the VCF file just 1 time, not between 4 to 6 times for nothing...

This issue is fixed now. For empty fields we should detect what is an empty field and just delete the field in the `fields` table.
It's another less important issue (there is no drawback to use a db file with such content, except GUI comfort).

**Comment by dridk** [comment]
seriously ?? you fixed this ??  This is awesome  !

**Comment by ysard** [comment]
Yes we do not require the exact number of variants. I read just the the first 15000 lines and i make an average of the bytes per line.
At this scale I don't even need to remove the headers.
This bytes average is used with the full size of the opened file to make an evaluation.
Full size is also present in the last 4 bytes of a gz compressed file => no need to uncompress it.
