### ISSUE TITLE
make LOGGER easier

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#163]
Actually, to use the logger we have to import LOGGER, and create an instance : 

```python
from cutevariant.common import logger
LOGGER = cm.logger()
```

Its really borring, that's why I don't use it too much. 
I suggest to make in simple without instance requirement : 

```python
from cutevariant.common import logger
logger.info("salut") 
```

**Comment by ysard** [comment]
In my opinion logging is not so much used because when a loglevel is selected, it is applied to the full project.
Thus the ouput is quickly unreadable, especially when you are interested in a specific use case (SQL queries, plugins, GUI, etc.).
So the logs are disabled/commented when they no longer seem useful. I also do this and this is bad!

The problem is that i don't know for now, how to limit logging per module. With a filter maybe.
By importing a unique object in all modules, i think it will not be possible to pass something like an argument to a local logger to allow further filtering of the current module.

Let's give ourselves time to think about something cleaner; and let's not waste time implementing / merging this on the devel branch for now.

Also... it is not boring to add 1 line at the top of each module, i now know why there is so few code documentation :D
