### ISSUE TITLE
refactor VQL/PYTHON/SQL function

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#180]
![image](https://user-images.githubusercontent.com/1911063/97002738-b1c9a200-153a-11eb-8f32-5425c0acb787.png)

We should refactor a little to keep according with the representation above . For instance some renaming can be done

### Naming 
- from_vql  is already avaible  and it is called "parse_vql" 
https://github.com/labsquare/cutevariant/blob/69cbf27220991d8f0311345411cd8d3efb2895a3/cutevariant/core/vql.py#L282

- to_vql is already avaible from querybuilder and it is called "build_vql_query"
https://github.com/labsquare/cutevariant/blob/69cbf27220991d8f0311345411cd8d3efb2895a3/cutevariant/core/querybuilder.py#L337

- to_sql is already avaible from querybuilder and it is called "build_query"
https://github.com/labsquare/cutevariant/blob/69cbf27220991d8f0311345411cd8d3efb2895a3/cutevariant/core/querybuilder.py#L362

**Comment by ysard** [comment]
build_query is renamed to build_sql_query.

build_complete_query should be renamed build_full_sql_query... Moreover it should be used instead of build_sql_query because it wraps the query of samples and tables of the database and avoids useless code duplication. We also need some caching methods here.

The "query" term in build* functions is important because we need to now that we are not building a VQL object or something else.
