### ISSUE TITLE
PedReader should not test complementary with sample db

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#196]
PedReader should be only a pedfile reader. Testing compatibility with sample DB is not a good idea. 

Actually, there is a bug due to this : 

I tried to reproduce to SnpEff protocol : https://pcingola.github.io/SnpEff/examples/
VCF and pedfile are here : https://github.com/jmchilton/SnpEffect/tree/master/papers/Protocol/data 

This is okay : 
![image](https://user-images.githubusercontent.com/1911063/98810096-f13f2c00-241e-11eb-9491-53f40fe02543.png)

But this is not : 

![image](https://user-images.githubusercontent.com/1911063/98810179-19c72600-241f-11eb-8af2-2ca96b972bda.png)

I investigate the bug, and I think I find the problem : 

when no pedifile are available, cutevariant create  samples with "fam" as familly_id. 
when importing a pedfile, cutevariant is trying to update sample data . 
But the PedReader doesn't return anything because there is a constraints telling : 

'''ERROR: [pedreader.py:162:get_samples()] PED file conformity line <6>; sample (family_id, individual_id):<CEPH_1463, NA12878> not found in database'''

**Comment by dridk** [comment]
I fixed the bug in another branch waiting your approval. 
We must fix this quickly, because I published a  documentation here which reproduce the SnpEff examples : 
https://github.com/labsquare/cutevariant/wiki/Usage-examples

**Comment by ysard** [comment]
I don't really have time to spend on the project now :(

> '' 'ERROR: [pedreader.py:162:get_samples ()] PED file conformity line <6>; sample (family_id, individual_id): <CEPH_1463, NA12878> not found in database '' '

From memory you told me that the family ids were "fam" by def (I agree that this is not in the norm).
In fact until now, one would expect to handle *.tfam files which contain the family identifier "fam" (same default name as in the DB).

The problem is that VCF files don't appear to have a family identifier in their data (?) And PLINK files rely on it to ensure the integrity of the data being processed.

We are in a very particular case here where the notion of uniqueness actually comes from the VCF and not you PLINK. The unique key is indeed (family_id, sample_id); relying only on sample_id will one day pose problems in the uniqueness of the data handled.

You have to do a fallback with an argument "i_dont_care_of_family_id = True" in the reader because one day we will use this reader thinking that it correctly implements the standard and we will have some great surprises.

And document that ...

[EDIT] The readers should implement the norm of the files they open as much as possible, and thus control input data...
