### ISSUE TITLE
Performance issue with large dataset

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#198]
I m using the tutorial from here : 
https://github.com/labsquare/cutevariant/wiki/Usage-examples 

Showing variant from the following query is extremly fast  ! Even when displaying the last page  
```SELECT favorite,chr,pos,ref,alt FROM variants ```

But when you try to show an annotation like "gene" or "impact"... It is really slow ... 

```SELECT chr, pos, gene FROM variants ```

All the time, it comes from counting variant ! We must do some optimization ! ( caching etc ... )

**Comment by ysard** [comment]
Querying the table is slow because the file is big.

There are 2 origins to this delay:
- loading the project file in the disk cache of the operating system
- its querying

You can index a few more columns (which I was planning to do one day):
gt of samples_has_variant, and gene, impact, consequence, biotype of annotations.

Remember that too many indexes lead to 2 things:
- complexity of the query plan
- increase in file size due to redundancy of stored data. This ultimately leads to even more slowness when you have to load the project on first reading.

## COUNT slowness
The "count" will always be long, there is no way to shorten it.
However, it is important to note that it is not the count that is long, but the DISTINCT on the temporary results before the aggregate function COUNT.
**Temporary results require no more and no less to browse the entire database**. There is no way to anticipate this since the query depends on the columns selected by the user.

=> use EXPLAIN QUERY PLAN to debug.

### Improving COUNT
Regarding the cache, I optimized everything I could. As it is, you won't have more perfs with SQLite here. It is not excluded that certain RDBMSs present optimizations to recalculate the intermediate states of the requests. 
In fact some RDBMSs can use COUNT slicing techniques in batch modes.
See this example which manages to make a count in 15ms on 150 million lines.
https://www.brentozar.com/archive/2019/12/how-to-make-select-count-queries-crazy-fast/

Be careful though, the query is very simple, and it doesn't say that performance is maintained in real use cases:
SELECT COUNT (*) FROM dbo.Votes;

BTW, this is not the subject here since we are related to SQLite.

### Important note about threading and caching:
Each thread has a cache that is independent for each decorated function that uses an SQL connection.
There are 3 threads, therefore it takes a maximum of 3 full recalculations of queries to be 100% sure to have a hit.

Oddly enough, it's the threading that poses a problem: the interface remains reactive but the chances of having a hit in the cache are divided by 3.

=> **One idea would be to use a custom implementation of the lru_cache decorator that does not take into account the SQL connection argument in its unique key**.

However, for a new request, the count will always be as slow and nothing will help.


I prevent the usual ideas:
- It's not due to the joins
- This is not due to the SQLite cache size (unless, perhaps, to allow 20GB of RAM for the project)

**Comment by dridk** [comment]
If it is not due to to join. Why it is faster when a query fields only from variant tables ?

**Comment by dridk** [comment]
looks better now since i use Thread and compute count separately
