### ISSUE TITLE
Easier way to filter tags

### ISSUE THREAD

**Issue by SamuelNicaise** [labsquare/cutevariant#276]
To filter out variants with the "bruit" tag, right now we use the following filter:
tags ~ ^(?!.\*?(?:bruit)).\*$

This is not very intuitive for less tech-savy users. Maybe there could be an easier way to deal with excluded values in lists?

**Comment by dridk** [comment]
WHERE tags HAS "bruit"

**Comment by dridk** [comment]
Why not using : 

tags ~ "bruit"

**Comment by antonylebechec** [comment]
In order to select specific "tags" or "consequences", the "HAS" operator seems to be an easy way. However, it's seems to not work. 
This example shows the selection of variants with the exact "consequence" "intron_variant", but not the variant "splice_region_variant&intron_variant". The same with "tags".
Moreover, operator "NOT HAS" 


Example with "ann.consequence"

SELECT favorite,classification,tags,chr,pos,ref,alt,ann.consequence FROM variants
![image](https://user-images.githubusercontent.com/40463532/126485590-7a795331-82bb-4be9-90a7-b94bae8bb6ba.png)



SELECT favorite,classification,tags,chr,pos,ref,alt,ann.consequence FROM variants WHERE ann.consequence HAS 'intron_variant'
![image](https://user-images.githubusercontent.com/40463532/126485644-4a87ad87-3a9d-4b7d-b784-f0a98ea77777.png)


Example with "tags"
SELECT favorite,classification,tags,chr,pos,ref,alt,ann.consequence FROM variants WHERE tags HAS 'bruit'
![image](https://user-images.githubusercontent.com/40463532/126486385-ccd19663-bd32-4ebc-8608-d77038dd1f84.png)


SELECT favorite,classification,tags,chr,pos,ref,alt,ann.consequence FROM variants WHERE tags NOT HAS 'bruit'
TextXSyntaxError

**Comment by dridk** [comment]
![has_feature](https://user-images.githubusercontent.com/1911063/126716964-81044e93-5a4b-429f-bc67-d60e8019f7d5.gif)
