### ISSUE TITLE
Handle bad (biologist) files

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#45]
The SQL code used for the insertion of the data is not resistant to the stupidities which one can find in files of users (biologists).

We have to design a test file with the worst things we can imagine.

Some proposals to implement (PS: I already know that these things will crash the code):
- [x] Variant duplication
- [ ] Duplicate annotations for the same variant
- [ ] Duplication of samples for the same variant
- [x] Annotations with missing/additional fields compared to the others
- [ ] Variants with same chr,pos and different ref,alt (test behavior of the count queries)

**Comment by Aluriak** [comment]
Some ideas:

- [ ] use `а` instead of `a` for two otherwise identical entries (or `Ѕ` and `S`, or [any other](https://en.wikipedia.org/wiki/Cyrillic%5Fscript)). Ensure errors are raised for any non-ascii value. [Unidecode](https://pypi.org/project/Unidecode) may help.
- [ ] expect user to occasionally provides you non-unicode files. [Chardet](https://pypi.org/project/chardet) may help.

At some point, a function `validate_input` should take a filename/linestream in input, and raise/yield `ValueError` for any encountered problem. It would be easy to test such a function, and to run it on any given file.

**Comment by dridk** [comment]
We may validate json output from reader using json shema
https://pypi.org/project/jsonschema/

**Comment by dridk** [comment]
I found something similar for validating dict instead json :

https://pypi.org/project/schema/

@see #53

**Comment by dridk** [comment]
https://fr.wikipedia.org/wiki/Fuzzing
