### ISSUE TITLE
use vacuum after import

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#99]
https://www.sqlitetutorial.net/sqlite-vacuum/

**Comment by dridk** [comment]
We are using DBS of 50 GB+ on our platform. no complains works great. Make sure you are doing everything right! Are you using predefined statements ? *SQLITE 3.7.3

Transactions
Pre made statements
Apply these settings (right after you create the DB)

PRAGMA main.page_size = 4096;
PRAGMA main.cache_size=10000;
PRAGMA main.locking_mode=EXCLUSIVE;
PRAGMA main.synchronous=NORMAL;
PRAGMA main.journal_mode=WAL;
PRAGMA main.cache_size=5000;
Hope this will help others, works great here

**Comment by ysard** [comment]
Please, RTFM.

https://sqlite.org/pragma.html

# page_size
- 4096 par def depuis SQLite 3.12
- à faire **avant la création** d'une table ou **avant un VACUUM** si la table existe déjà

=> faire ça en l'air, après la création n'a aucun sens
Please, RTFM.

# cache_size
- `-2000` par def
- Ne dure que durant la session

- Si -N: le cache est alloué à N*1024 bytes (à partir de la 3.7.10)
- Si N: alloué à N pages

En pratique la requête `PRAGMA main.cache_size` renvoie chez moi 2000 et non -2000. Que faut-il en penser ?

Commentaire:
https://stackoverflow.com/questions/2182774/can-sqlite-load-10m-data-into-the-memory

> You should not change the page size unless you know what you're doing; it's the wrong thing to play with if you're trying to influence caching, and setting it to 5120 will probably have dire performance consequences. 

# locking_mode

NORMAL: a database connection unlocks the database file at the conclusion of each read or write transaction
EXCLUSIVE: never releases file-locks.
    - prevent other processes from accessing the database
    - number of system calls for filesystem operations is reduced
    - WAL databases can be accessed in EXCLUSIVE mode without the use of shared memory.

=> globalement inutile sauf si on cherche à économiser 3 milliardièmes de seconde de temps noyau qui se courent après.
=> on ne fait de toute façon pas d'accès multiples sur un projet

# journal_mode

- WAL is significantly faster in most scenarios.
- WAL provides more concurrency as readers do not block writers and a writer does not block readers. Reading and writing can proceed concurrently.
- many fewer fsync() operations and is thus less vulnerable to problems on **systems where the fsync() system call is broken**.
- WAL might be very slightly slower (perhaps 1% or 2% slower) than the traditional rollback-journal approach in applications that do mostly reads and seldom write.

=> ok sauf qu'on utilise pas d'accès concurrents
=> cas de niche, on économise encore 10 fsync par heure...
Please, RTFM.

# synchronous

- WAL mode is safe from corruption with synchronous=NORMAL
- The SQLite database engine will still sync at the most critical moments, but less often than in FULL mode.
- On the other hand, commits can be orders of magnitude faster with synchronous OFF.

# auto_vacuum

can be used to rebuild the entire database file and thus reclaim unused disk space.
"full", the freelist pages are moved to the end of the database file and the database file
is truncated to remove the freelist pages at every transaction commit. Note, however,
that auto-vacuum only truncates the freelist pages from the file. **Auto-vacuum does not
defragment the database nor repack individual database pages the way that the VACUUM command does.
In fact, because it moves pages around within the file, auto-vacuum can actually make fragmentation worse.**

**Therefore, auto-vacuuming must be turned on before any tables are created.
It is not possible to enable or disable auto-vacuum after a table has been created.**

=> totalement inutile
Please, RTFM.

# VACUUM, remarques plus générales

https://www.sqlitetutorial.net/sqlite-vacuum/

C'est pour les bases qui sont soumises à de gros changements liés à des opérations de création, update, ajout et suppression.
Dans notre cas la BDD est écrite une fois et ne bouge quasi plus.

Faut-il faire un VACUUM dans notre cas d'usage et à cet endroit : juste après la création en 1 transaction de millions de lignes contiguës ? NON.

Please, RTFM.

# Conclusion

Cherche t'on à optimiser les performances ou la sécurité? J'ai du mal à saisir le contexte d'utilisation de ces commandes. La plupart sont inutiles, voire contre-productives.

Existe t'il des gens qui connaissent parfaitement les implications de telles modifications sur le comportement d'un système et/ou d'un système devant manipuler des fichiers... de quelques centaines de Mo comme les nôtres.

Ça ressemble à des commandes copiées/collées et appliquées [sur un système non fiable] par des générations d'ingénieurs depuis qu'un génie a lu une fois la doc pour un cas d'usage bien particulier que l'Histoire a oublié.

Ce sont les mêmes légendes qui poussent les "ingé" à ne plus normaliser les bases parce-qu'un jour un génie a eu l'idée de dire que les jointures c'était moche et donc forcément non performant.

À titre de note:
SQLite 3.7.3: 2010-10-08
SQLite 3.7.10: 2012-01-16

20 ans de legacy ça va commencer à se voir. Même GenOuest a fait 1 mise à jour depuis...

Please, RTFM.
